# permissions for end users to edit networkaddresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkaddress-editor-role
rules:
- apiGroups:
  - conversion-webhook.example.zqzten.io
  resources:
  - networkaddresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - conversion-webhook.example.zqzten.io
  resources:
  - networkaddresses/status
  verbs:
  - get
